### PR TITLE
Big Changes...

### PR DESCRIPTION
**Pull request by ptsouchlos**
There are a lot of changes, but it boiled down to the following:
* Adding CMake support.
* Removing spaces from folders/files.
* Changing initialization of some (large) arrays that were using the `{}` method. 

I've structured it so that each folder in this source directory will be built as a seperate repository. If you ever need to create a new sub-project, just create a new directory (better to copy an existing one), edit the source, re-configure from cmake and re-build.

### CODE REVIEW

**Comment by ptsouchlos** [comment]
This directly addresses and resolves #1.

**Review by caveofprogramming — APPROVED** [review]

**Comment by caveofprogramming** [comment]
Compatible with cmake, thanks Paul

**Comment by caveofprogramming** [comment]
Many thanks Paul!!!

I don't really know what I'm doing with git, but I think I've 
successfully merged your changes into the main branch. Or something like 
that.

Let me know if you think anything's gone awry, but looks OK as far as I 
can see. I'll have to give cmake a proper go myself soon!!

Regards
John

**Comment by ptsouchlos** [comment]
@caveofprogramming No problem! And yes it looks like you successfully merged it into the master branch. 

Let me know if you have any issues setting the project up with cmake.

**Pull request merged**
